name: GitHub actions HW
on: 
  push:
    branches:
     - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say Hello
      run:  echo "Hello, GitHub Actions!"
