name: Python Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

permissions:
  contents: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say Hello
      run:  echo "Hello, GitHub Actions!"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=myapp --cov-fail-under=70
  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build Project
        run: |
          echo "Building the project..."

      - name: Add build badge to README
        run: |
          status_url="https://img.shields.io/github/workflow/status/ihorvyt/actions-hw/Python%20Tests%20and%20Build?label=Build&style=for-the-badge"

          if ! grep -q "![Build Status]" README.md; then
            sed -i "1s|^|![Build Status]($status_url)\n\n|" README.md
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add README.md
            git commit -m "Add build status badge"
            git push origin HEAD:main
          fi